CRIAR_TABELA= """
CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR UNIQUE NOT NULL
)
"""

INSERIR_USUARIO= """
    INSERT INTO usuarios (email)
    VALUES (?)
"""

PROUCURAR_USUARIO= """
    SELECT id, email FROM usuarios WHERE id = ?
"""